name: "Crovia · Evidence Presence (WEDGE)"
description: "Records whether auditable AI training evidence is present."
author: "Crovia"

branding:
  icon: "eye"
  color: "blue"

inputs:
  mode:
    description: "warn or fail"
    required: false
    default: "warn"
  root:
    description: "Root path to scan"
    required: false
    default: "."
  version:
    description: "WEDGE engine version: 1 or 2"
    required: false
    default: "1"
  badge:
    description: "(v2) Generate badge (.crovia/badge.svg)"
    required: false
    default: "false"
  pointer:
    description: "(v2) Generate signed pointer (.crovia/PTR-*.json)"
    required: false
    default: "false"

outputs:
  verdict:
    description: "CROVIA verdict: GREEN or RED"
    value: ${{ steps.crovia.outputs.verdict }}
  reason:
    description: "Reason for verdict"
    value: ${{ steps.crovia.outputs.reason }}
  primary:
    description: "Comma-separated list of evidence artifacts found"
    value: ${{ steps.crovia.outputs.primary }}
  critical_omissions:
    description: "Number of critical omissions detected"
    value: ${{ steps.crovia.outputs.critical_omissions }}
  verdict_path:
    description: "Path to .crovia verdict_latest.json"
    value: ${{ steps.crovia.outputs.verdict_path }}
  pointer:
    description: "(RED only) Path to EVIDENCE.pointer.json"
    value: ${{ steps.crovia.outputs.pointer }}

runs:
  using: "composite"
  steps:
    - run: python3 -m pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - id: crovia
      run: |
        if [ "${{ inputs.version }}" = "2" ]; then
          python3 ${{ github.action_path }}/src/check_v2.py
        else
          python3 ${{ github.action_path }}/src/check.py
        fi
      shell: bash
      env:
        CROVIA_MODE: ${{ inputs.mode }}
        CROVIA_ROOT: ${{ inputs.root }}
        CROVIA_BADGE: ${{ inputs.badge }}
        CROVIA_POINTER: ${{ inputs.pointer }}
